// <auto-generated />
using System;
using System.Numerics;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VotaFacil.Infra.Data.Contexto;

#nullable disable

namespace VotaFacil.Infrastructure.Migrations
{
    [DbContext(typeof(VotacaoContext))]
    [Migration("20241010001650_SmartContracts")]
    partial class SmartContracts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EleicaoCandidato", b =>
                {
                    b.Property<Guid>("EleicaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidatoId")
                        .HasColumnType("uuid");

                    b.HasKey("EleicaoId", "CandidatoId");

                    b.HasIndex("CandidatoId");

                    b.ToTable("EleicaoCandidato", (string)null);
                });

            modelBuilder.Entity("Nethereum.Hex.HexTypes.HexBigInteger", b =>
                {
                    b.Property<string>("HexValue")
                        .HasColumnType("text");

                    b.Property<BigInteger>("Value")
                        .HasColumnType("numeric");

                    b.ToTable("HexBigInteger");
                });

            modelBuilder.Entity("VotaFacil.Domain.Entidades.EleicaoModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlockNumberString")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("block_number");

                    b.Property<string>("ContractAddress")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)")
                        .HasColumnName("contract_address");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<DateTime>("Fim")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fim");

                    b.Property<string>("GasUsedString")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gas_used");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inicio");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("TransactionHash")
                        .IsRequired()
                        .HasMaxLength(66)
                        .HasColumnType("character varying(66)")
                        .HasColumnName("transaction_hash");

                    b.HasKey("Id");

                    b.ToTable("eleicao");
                });

            modelBuilder.Entity("VotaFacil.Domain.Entidades.EleitorModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<string>("EnderecoEthereum")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("endereco_ethereum");

                    b.Property<string>("Identificador")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("identificador");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("eleitor");
                });

            modelBuilder.Entity("VotaFacil.Domain.Entidades.LoginModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("EleitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("eleitor_id");

                    b.Property<DateTime?>("ExpiracaoToken")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiracao_token");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean")
                        .HasColumnName("status");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_login");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("EleitorId")
                        .IsUnique();

                    b.ToTable("login");
                });

            modelBuilder.Entity("VotaFacil.Domain.Entidades.VotoModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CandidatoId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidato_id");

                    b.Property<DateTime>("DataHoraVoto")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora_voto");

                    b.Property<Guid>("EleitorId")
                        .HasColumnType("uuid")
                        .HasColumnName("eleitor_id");

                    b.Property<string>("HashAnterior")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_anterior");

                    b.Property<string>("HashAtual")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_atual");

                    b.Property<string>("NumeroBloco")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero_bloco");

                    b.Property<Guid>("VotacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("votacao_id");

                    b.HasKey("Id");

                    b.HasIndex("CandidatoId");

                    b.HasIndex("EleitorId");

                    b.HasIndex("VotacaoId");

                    b.ToTable("voto");
                });

            modelBuilder.Entity("VotaFacil.Domain.Model.CandidatoModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("FotoPath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("foto");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("candidato");
                });

            modelBuilder.Entity("VotaFacil.Domain.Model.ContaEthereumModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(42)
                        .HasColumnType("character varying(42)")
                        .HasColumnName("address");

                    b.Property<string>("PrivateKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("private_key");

                    b.HasKey("Id");

                    b.ToTable("conta_ethereum");
                });

            modelBuilder.Entity("EleicaoCandidato", b =>
                {
                    b.HasOne("VotaFacil.Domain.Model.CandidatoModel", null)
                        .WithMany()
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EleicaoCandidato_Candidato");

                    b.HasOne("VotaFacil.Domain.Entidades.EleicaoModel", null)
                        .WithMany()
                        .HasForeignKey("EleicaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EleicaoCandidato_Eleicao");
                });

            modelBuilder.Entity("VotaFacil.Domain.Entidades.LoginModel", b =>
                {
                    b.HasOne("VotaFacil.Domain.Entidades.EleitorModel", "Eleitor")
                        .WithOne("Login")
                        .HasForeignKey("VotaFacil.Domain.Entidades.LoginModel", "EleitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eleitor");
                });

            modelBuilder.Entity("VotaFacil.Domain.Entidades.VotoModel", b =>
                {
                    b.HasOne("VotaFacil.Domain.Model.CandidatoModel", "Candidato")
                        .WithMany("Votos")
                        .HasForeignKey("CandidatoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VotaFacil.Domain.Entidades.EleitorModel", "Eleitor")
                        .WithMany("Votos")
                        .HasForeignKey("EleitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VotaFacil.Domain.Entidades.EleicaoModel", "Votacao")
                        .WithMany("Votos")
                        .HasForeignKey("VotacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidato");

                    b.Navigation("Eleitor");

                    b.Navigation("Votacao");
                });

            modelBuilder.Entity("VotaFacil.Domain.Entidades.EleicaoModel", b =>
                {
                    b.Navigation("Votos");
                });

            modelBuilder.Entity("VotaFacil.Domain.Entidades.EleitorModel", b =>
                {
                    b.Navigation("Login")
                        .IsRequired();

                    b.Navigation("Votos");
                });

            modelBuilder.Entity("VotaFacil.Domain.Model.CandidatoModel", b =>
                {
                    b.Navigation("Votos");
                });
#pragma warning restore 612, 618
        }
    }
}
